### ISSUE TITLE
This works, sometimes...

### ISSUE THREAD

**Issue by cuni0716** [AtomLinter/linter-php#115]
Somedays this package lints my php code on the fly and sometimes don't have anything.

**Comment by Arcanemagus** [comment]
Remember that this _only_ runs `php -l` on your code, which catches only the worst syntax errors in your code as it is quite simplistic. You might be looking for something more along the lines of [linter-phpcs](https://github.com/AtomLinter/linter-phpcs) for code style checking, or [linter-phpmd](https://github.com/AtomLinter/linter-phpmd) for common code issues checking.

I know when I'm coding it's rare that I see an error from this, but that's only due to how little it actually checks.

I'm going to mark this as closed, but if you see something you feel it should be warning about, _and_ `php -l` shows a message for the file at that state I would love for you to re-open this with the example since that would be a bug.

**Comment by cuni0716** [comment]
Ohhhh, okk! Thanks!
