### ISSUE TITLE
Activate only on file save

### ISSUE THREAD

**Issue by pixmin** [AtomLinter/linter-php#122]
At the moment the linter runs while writing the code, which I find annoying, it would be nice to have an option to only activate it when the file is saved (as the HTML/CSS linter does)

**Comment by Arcanemagus** [comment]
You can disable this (for all linters) in the `linter` package settings by turning off linting on the fly. Alternatively you can bump the delay between lint triggers up in the same settings (I have mine set to `2000` ms myself).

That being said if you want the ability to toggle that for _just_ this linter, I wouldn't be opposed to a PR toggling `lintOnFly` via a setting.

**Comment by Arcanemagus** [comment]
@pixmin Are you interested in writing this PR? If not I'm going to mark this as closed since this functionality already essentially exists in the `linter` package. If you want something to disable it for certain projects only you might look into [project-manager](https://atom.io/packages/project-manager).

**Comment by pixmin** [comment]
Thanks, using the `linter` package setting works
