### ISSUE TITLE
Line number (188) greater than maximum line (187)

### ISSUE THREAD

**Issue by BlixsoftMexico** [AtomLinter/linter-php#180]
Hello!
Let me know how to solve this problem, does not allow me validation code after line 187.

Thank you

```
Error: Line number (188) greater than maximum line (187)
Error: Line number (188) greater than maximum line (187)
    at Object.rangeFromLineNumber (C:\Users\Diego Flores\.atom\packages\linter-php\node_modules\atom-linter\lib\index.js:178:11)
    at file:///C:/Users/Diego Flores/.atom/packages/linter-php/lib/main.coffee:58:30
    at process._tickCallback (node.js:392:9)
```

**Comment by Arcanemagus** [comment]
Are you able to share the file this is showing up on?

**Comment by BlixsoftMexico** [comment]
Hello!
no longer displays the error, it seems to be solved by restarting the computer but should resubmit the fault, I will be sending the corresponding cuptura.

Thank you

**Comment by BlixsoftMexico** [comment]
Hello!
Again the error has appeared, this time attached screenshot.

Thank you
![error](https://cloud.githubusercontent.com/assets/20438926/16912103/f05e174a-4ca7-11e6-87ad-ac340f06b808.png)

**Comment by Arcanemagus** [comment]
If I had to guess, this is due to the delay between the following steps:

* An edit triggers a lint
* The file contents are sent off to `php` to be checked (last line is 164)
* You make a further change, removing one line from the file (last line is now 163)
* Some error triggers a message on the last line of the file (last line is 164 as `php` saw it), which `php` then sends back to be displayed
* When the error message from PHP is sent back, this error is triggered since the contents have been modified since the lint was triggered

Unfortunately there isn't really anything that can be done about this, as we have no way to know whether that invalid range can be safely attributed to this sequence of events, or whether `php` is returning invalid data.
