### ISSUE TITLE
linter php can't work 

### ISSUE THREAD

**Issue by lalitaryan1993** [AtomLinter/linter-php#233]
```
Error: spawn C:\xampp\php ENOENT
    at getENOENTError (C:\Users\LALIT AMIT\.atom\packages\linter-php\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\LALIT AMIT\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

please help me

**Comment by Arcanemagus** [comment]
What is the output of `where.exe php`? The _full_ output should be set in the Settings, in your case I'm guessing you need to have `C:\xampp\php.exe` in there, but I've never installed PHP through XAMPP so I can't say for sure.

**Comment by Arcanemagus** [comment]
Closing due to a lack of response, if you are still having issues please report back!

**Comment by roddypratt** [comment]
Similar problem here - I have Atom Linter working with Typescript, but not PHP.  PHP errors are not shown in Atom, even though php -l <filename> shows errors.
```
php -l index.php
PHP Parse error:  syntax error, unexpected ';' in index.php on line 11
 
Parse error: syntax error, unexpected ';' in index.php on line 11
Errors parsing index.php
```
Linter debug shows this
```
Platform: win32
Atom Version: 1.17.2
Linter Version: 2.1.4
All Linter Providers: 
  - PHP
  - TSLint
Matching Linter Providers: 
  - PHP
Disabled Linter Providers; 
Current File scopes: 
  - *
  - text.html.php
  - meta.embedded.block.php
  - source.php
  - comment.line.double-slash.php
```

`where.exe php` shows `C:\php\php.exe` which is what I have in the package settings. I have composer installed, and the Atom errors about php/composer have now stopped, but Atom linter pane shows nothing. 

Is there a specific requirement for 32bit or 64bit php.exe?

**Comment by roddypratt** [comment]
OK, a follow-up. Turns out the problem was due to a weird project directory structure, and the `core.excludeVcsIgnoredPaths` setting (which was true). 

Basically I had a directory structure `A/B/myfile.php`. `A` contained a `.gitignore` file which ignored `B`.  In Atom, I had done "Open Folder..." on B (which had no .gitignore file or repository)   but I guess the code had looked up the tree 'beyond' the atom 'project folder' to locate a .gitignore. 

Not sure if bug, but certainly one to watch out for.
