### ISSUE TITLE
linter-php: Unable to determine PHP version

### ISSUE THREAD

**Issue by quentin42160** [AtomLinter/linter-php#237]
Hi, i have installed the package on twice computers.
On the first, the package works but on the other i have this error : 
```
linter-php : Unable to dertermine PHP version
Unable to determine the version of 'C:/php/php.exe' please verify that this is the right path to PHP. If you believe you have fixed this probleme please restart Atom
```

So i check the PATH and follow every help i found but nothing worked.

For every computers i have installed the same PHP version (5.6.30), in the same path.
One is on Windows 10 and the other is on windows 7 where i have manually install the package.

How can i identify the problem ?

**Comment by Arcanemagus** [comment]
What do you get when you run `where.exe php` on the computer where it isn't working?

**Comment by quentin42160** [comment]
I have to try this command in the windows shell ?

**Comment by Arcanemagus** [comment]
Correct, I suspect something is wrong with the setup of PHP on the system where it isn't working properly.

**Comment by quentin42160** [comment]
I have used the same setup.
I tried the command on both of my computers but they respond the same error : 
`Information: Can not find files for the specified model (s).`

**Comment by Arcanemagus** [comment]
That message means that you don't have `php` in your `%PATH%`. Are you sure that you have the PHP executable in the same place on both systems?

**Comment by quentin42160** [comment]
Thank for your answer.
I have desinstalled and reinstalled atom with the most recent update, i have also updated Linter to 2.1.0 and this error has disappeared but Linter-php does'nt correct my code.

**Comment by Arcanemagus** [comment]
I actually have removed that check from this package since then, since for _most_ cases it was just being buggy. In your case though it was doing what it was originally intended and showing there was a configuration problem.

You need to either specify the _full_ path to PHP (eg. `C:\php7\php.exe` on my system) in the settings, or you need to add the directory containing PHP to your `%PATH%`.

**Comment by quentin42160** [comment]
This is my settings :
![capture1](https://cloud.githubusercontent.com/assets/8959517/24247433/fca13b30-0fcb-11e7-91de-953d8731293b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8959517/24247436/fdaf0764-0fcb-11e7-96dd-e19263b6ffbd.PNG)

Have i done something wrong ?
Else i want to try the second option how can i add the PHP directory to my PATH ?

**Comment by Arcanemagus** [comment]
You would need to add `C:\php7` to your PATH ([howto](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/)).

The above settings _should_ be working though, if you want to try to debug this faster you can contact me on [Atom's Slack](http://atom-slack.herokuapp.com/), otherwise are you seeing anything in the Console under Atom's Developer Tools?

**Comment by quentin42160** [comment]
In fact i can't run php when i launch php.exe there are a missing module in this computer, i will try to repair this.

Thanks for your help.
