### ISSUE TITLE
Error running PHP Error: "php"

### ISSUE THREAD

**Issue by DonkihotD** [AtomLinter/linter-php#246]
Occurs at any action in the PHP script

![](https://cloud.githubusercontent.com/assets/17106272/25049380/0485db12-215b-11e7-98f2-965f86da8799.png)

**Comment by Arcanemagus** [comment]
It looks like your shell isn't using an encoding that the console understands unfortunately, but I would guess that the issue is that you don't have PHP in the `%PATH%` for your system. You can either fix this by adding the location where you have it installed to your `PATH` environment variable, or by setting the path manually in the settings.

**Comment by rubielhum** [comment]
Hello and how it's done

**Comment by Arcanemagus** [comment]
@rubielhum Assuming you mean editing your `PATH`, that would depend on your operating system.
