### ISSUE TITLE
Failed to spawn on Windows

### ISSUE THREAD

**Issue by robingram** [AtomLinter/linter-php#6]
Since installing the new installer based version of Atom (currently 0.158.0) on Windows 7 I am getting the following error when starting the editor:

"Failed to spawn command php. Make sure php is installed and on your PATH"

I don't get the error if I uninstall linter-php. I've also tried uninstalling and re-installing.

Php is in my path and in addition I have the following in my config.cson:

    'linter-phpcs':
      'phpExecutablePath': 'C:/Program Files (x86)/php'

Previously, using Atom installed from the zip file the linter was working properly.

**Comment by Cipa** [comment]
after adding 
process.env.PATH = ["/Users/iMac/pear/bin/", process.env.PATH].join(":")
to init.cofee the error doesn't appear but when I run phpcs from command line like
/Users/iMac/pear/bin/phpcs

I get 


Warning: include_once(PHP/CodeSniffer/CLI.php): failed to open stream: No such file or directory in /Users/iMac/pear/bin/phpcs on line 21

Warning: include_once(): Failed opening 'PHP/CodeSniffer/CLI.php' for inclusion (include_path='.:') in /Users/iMac/pear/bin/phpcs on line 21

Fatal error: Class 'PHP_CodeSniffer_CLI' not found in /Users/iMac/pear/bin/phpcs on line 24


So in all cases it could be the phpcs is not properly installed. Maybe because php was installed with MAMP or WAMP or something similar

**Comment by funsterisdafunniest** [comment]
@Cipa are you not mistaking this repo with linter-phpcs? the linter in this project only use php

@robingram did this issue still persist?

**Comment by Cipa** [comment]
Probably, I currently have phpcs disabled and linter-php enabled, I don't get php lint problems anymore.

**Comment by robingram** [comment]
Was definitely using this linter. Not sure where I got those settings from though, long time ago now. Anyway, the issue didn't persist

**Comment by funsterisdafunniest** [comment]
@robingram well then, i guess it's okay to close the issue?

@kevinsawicki

**Comment by robingram** [comment]
Fine with me.

Rob.

-- 
headcrash.org

Sent by my android

**Comment by steelbrain** [comment]
Please re-open another issue if it's still an issue after latest update

**Comment by seagomezar** [comment]
I had the same problem on Ubuntu 14.04LTS, and I installed the php5-cli and works fine for me.
I just run sudo apt-get install php5-cli

**Comment by twoelevenjay** [comment]
I had the same problem on Mac OSX, and restarting the machine solved it.
