### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by Elexy** [AtomLinter/linter-php#61]
I just wanted to ask how to set indentation to 2 spaces instead of 4

**Comment by Arcanemagus** [comment]
I'm closing this as this has nothing to do with `linter-php`.

I'm going to make several assumptions here and guess you are using Atom since you are filing an issue on this repo. If that is correct you would just go to your settings, check `Soft Tabs`, and set the `Tab Length` to 2.

You should probably check out the [Atom Flight Manual](https://atom.io/docs/v1.0.5/) to get you started with this editor. If something isn't answered in there, the [Atom Discussion](https://discuss.atom.io/) forum is a better place for this sort of question.

**Comment by Elexy** [comment]
Sorry, I didn't realize linter-php can be used with other editors as well.

I created a question here. 

Tnx
