### ISSUE TITLE
Linter should activate when Atom is launched & files are already open

### ISSUE THREAD

**Issue by jblz** [AtomLinter/linter-php#92]
If I quit Atom and reopen it, files that were already open (from the previous session) do not activate the linter (even when explicitly telling it to `Linter: Lint` in the command palette).

If I manually open a PHP file using any method, linting then works as expected across previously open files.

I'm pretty new to Atom altogether, but I'd guess this is a regression due to #87.

Thanks & I'm happy to provide more info if needed!

**Comment by Arcanemagus** [comment]
This is actually [this](https://github.com/atom/atom/issues/8313) Atom issue again, which is exposed by #87.

You can force installation of v1.1.0 by running `apm install linter-php@1.1.0`, or just (re)open a PHP file until that bug is fixed. Marking this as closed as it isn't an issue with this package.

**Comment by jblz** [comment]
Thanks for the explanation & workaround!
